import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

import ChakraUIProvider from './components/ChakraUIProvider';

const roboto = Roboto({
	subsets: ['latin'],
	weight: '400',
});

export const metadata: Metadata = {
	title: 'Interactive Chart',
	description: 'Generated by create next app',
};

type RootProps = { children: React.ReactNode };

export default function RootLayout({ children }: RootProps) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<ChakraUIProvider>{children}</ChakraUIProvider>
			</body>
		</html>
	);
}
