'use client';

import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { CacheProvider } from '@chakra-ui/next-js';
import { ChakraProvider } from '@chakra-ui/react';
import './globals.css';

const roboto = Roboto({
	subsets: ['latin'],
	weight: '400',
});

export const metadata: Metadata = {
	title: 'Interactive Chart',
	description: 'Generated by create next app',
};

type RootProps = { children: React.ReactNode };

export default function RootLayout({ children }: RootProps) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<CacheProvider>
					<ChakraProvider>{children}</ChakraProvider>
				</CacheProvider>
			</body>
		</html>
	);
}
